sonar.projectKey=ticketera-nestjs
sonar.projectName=Ticketera Nestjs
sonar.sources=apps,libs
sonar.exclusions=**/node_modules/**,**/dist/**,**/*.spec.ts,**/*.d.ts
sonar.tests=apps,libs
sonar.test.inclusions=**/*.spec.ts
sonar.sourceEncoding=UTF-8
sonar.javascript.lcov.reportPaths=coverage/lcov.info
